export enum ActionType{
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAIL = 'REGISTER_FAIL',
    SET_AUTH_LOADING = 'SET_AUTH_LOADING',
    REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING',
    LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS',
    LOAD_USER_FAIL = 'LOAD_USER_FAIL',
}

