import type { NextPage } from 'next'
import Head from 'next/head'
import NavBar from '../components/NavBar'
import { useDispatch } from 'react-redux'
import {registerUser} from '../state/actions/auth';
import React from 'react';

const Home: NextPage = () => {

  const dispatch = useDispatch()

  const btnClick = (e:React.MouseEvent<HTMLElement>) => {
    e.preventDefault();
    if (dispatch && dispatch !== null && dispatch !== undefined){
      dispatch(registerUser())
    }
      
  }

  return (
    <div>
      <Head>
        <title>Welcome | Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar/>
      <button className='bg-blue-400 rounded' onClick={btnClick}>Click ME</button>
    </div>
  )
}

export default Home
